### ISSUE TITLE
URL of iOS App not recognised

### ISSUE THREAD

**Issue by Tuphal** [supergeorg/Grocy-SwiftUI#11]
I installed the app via the appstore without problem.
But after scanning the API QR-code, I can not connect.
I'm running PiHole with local DNS entry to resolve net.mydomain.de -> 10.10.20.3
When I use the manuall connection in the app and use the IP directly, it works.

Resolving the DNS via Safari or other Apps (DSfile/DSphoto..) I have no problems

Edit:
In the App-Log I see: "GrocyViewModel.checkServer():119 - error at checkLoginInto: serverError"
(Second problem: the App-Log can not be scrolled, I only see the first page)

**Comment by supergeorg** [comment]
Have you installed the server in a subdirectory (maybe even on the Pi-Hole device like I have)?

I guess that you get a connection error, please tell me if it is a real URL (like net.mydomain.de/api) or only a subfolder string (like /grocy/public/api).

**Comment by Tuphal** [comment]
Grocy is running on my Synology Docker with following image:
https://registry.hub.docker.com/r/linuxserver/grocy/

the API-site is without subdirectory:
![grafik](https://user-images.githubusercontent.com/42291781/119820271-93bd8900-bef1-11eb-8820-63f8a29ebc61.png)

**Comment by supergeorg** [comment]
Yeah, the docker setup seems normal and doesn't have any special setup for Grocy (it only copies config-dist.php to config.php).
I am interested in the scheme of the decoded QR code, since you said it worked when you entered the data manually. If the address shown in the screenshot is decoded in the QR code, then there shouldn't be any problem. If it isn't, please check your `BASE_URL `, it determines what gets shown by the QR.

**Comment by Tuphal** [comment]
the QR code is decoded in following URL:
net.mydomain.de:8082/api%7C<API-key>
this is also correctly shown in the manual connection tap.

Connection with net.mydomain.de:8082 is not working.
Connection with 10.10.20.3:8082 works perfectly.

**Comment by supergeorg** [comment]
Please check if it is relevant with the correct configuration and a newer app version.
If this is the case, please reopen this issue.
