### ISSUE TITLE
Quick Scan: Purchase a product after barcode is added

### ISSUE THREAD

**Issue by goaround** [supergeorg/Grocy-SwiftUI#117]
If I scan a barcode in "Quick-Scan" and the barcode is not in the database, I've to assign it to a product or create a new product. But then the dialog closes, and I have to scan the barcode again to purchase the product.

I would suggest opening the purchase dialog after the barcode has been assigned, or a new product has been created.

**Comment by supergeorg** [comment]
Well, it is kinda the intended behavior.
By scanning the code twice, you can check if it was added successfully. But I will look into making this behavior optional.

**Comment by Hoffelhas** [comment]
Hi, any update on this feature? A similar issue happens when you use 'consume' btw. You first need to add the barcode, but it would be very helpful if it immediately continues with the chosen function. Espscially if you have a lot of new items, it saves a lot of time if you don't need to scan everything twice. Scan, add barcode, and continue would be very helpful.

**Comment by supergeorg** [comment]
What is missing in the implementation in Grocy Mobile 2.4.2 and upwards?
There is a toggle in app settings which enables this feature.

**Comment by Hoffelhas** [comment]
Ah that's great! I guess this one can be closed then?
