### ISSUE TITLE
[MacOS] Text not fitting within UI elements

### ISSUE THREAD

**Issue by OmgImAlexis** [supergeorg/Grocy-SwiftUI#16]
<img width="664" alt="Screen Shot 2021-06-15 at 10 17 20 am" src="https://user-images.githubusercontent.com/6525926/121976472-1768e800-cdc3-11eb-8118-cd8299ed8a72.png">

Also the shadow that seems to be applied on a lot of the text is making it really hard to read.

<img width="181" alt="Screen Shot 2021-06-15 at 10 19 50 am" src="https://user-images.githubusercontent.com/6525926/121976558-3ebfb500-cdc3-11eb-8a76-bc708ae23306.png">

**Comment by supergeorg** [comment]
Oops, my bad. This should not be like this, but since I focussed mostly on iOS, it didn't hurt as much on macOS.

Should be fixed now (and since there was no 1.0.5 for macOS for now, this is now it)
<img width="535" alt="Screen Shot 2021-06-15 at 20 11 53" src="https://user-images.githubusercontent.com/24377292/122103025-6ab85600-ce16-11eb-8910-4d7896bfb0ab.png">
