### ISSUE TITLE
No connection to server

### ISSUE THREAD

**Issue by 1-ben-1** [supergeorg/Grocy-SwiftUI#25]
Hi, 

I have just downloaded the IOS app and I am able to scan the QR to which logs me in without an error, however, every screen (apart from settings) so the 'no connection to server error.

Grocy installed within a docker on a Synology NAS.

Please can you help?

Logs attached.

Many thanks

Ben

[Grocy-SwiftUI_LOG.log](https://github.com/supergeorg/Grocy-SwiftUI/files/6902960/Grocy-SwiftUI_LOG.log)

**Comment by supergeorg** [comment]
If I read `19:34:39.536 ERROR GrocyViewModel.requestData():257 - Data request failed for products. Message: decodingError(error: Swift.DecodingError.typeMismatch(Swift.String, Swift.DecodingError.Context(codingPath: [_JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "name", intValue: nil)], debugDescription: "Expected to decode String but found a number instead.", underlyingError: nil)))` correctly, some products have an integer (number) as their name? This is highly unusual, since name is clearly defined as string in the API.

**Comment by 1-ben-1** [comment]
Thank you, I noticed I have a product with a number instead of the name.

Thank you again for your help.

Ben
